Move all secrets to secrets directory

diff --git a/roles/git_pre_commit/templates/pre-commit.j2 b/roles/git_pre_commit/templates/pre-commit.j2
--- a/roles/git_pre_commit/templates/pre-commit.j2
+++ b/roles/git_pre_commit/templates/pre-commit.j2
@@ -1,22 +1,28 @@
 #!/bin/sh
 
-git diff --quiet HEAD -- ../../secrets
-rc=${?}
+set -x
 
-if [ ${rc} -eq 0 ]; then
-  echo "pre-commit: no changes in secrets directory"
+staged_secret_changes="$(git diff --staged --name-only HEAD --diff-filter=ACM -- secrets | xargs)"
+
+if [ -z "${staged_secret_changes}" ]; then
+  echo "pre-commit: no added or modified staged files in secrets directory"
   exit 0
 fi
 
-echo "pre-commit: changes in secrets directory, will try to encrypt"
+echo "pre-commit: added or modified staged files in secrets directory, will make sure they're encrypted"
 
-output="$(make encrypt_pre_commit)"
+output="$(make encrypt_pre_commit FILES="${staged_secret_changes}" 2>&1)"
 rc=${?}
 
 if [ ${rc} -eq 0 ]; then
-  echo "pre-commit: sensitive files encrypted successfully"
+  echo "pre-commit: staged files in secrets directory encrypted successfully"
   exit 0
 else
-  printf "pre-commit: failed to encrypt sensitive files:\n%s" "${output}"
-  exit 1
+  if [[ "${output}" =~ "input is already encrypted" ]]; then
+    echo "pre-commit: staged files in secrets directory were already encrypted"
+    exit 0
+  else
+    printf "pre-commit: failed to encrypt staged files in secrets directory:\n%s" "${output}"
+    exit 1
+  fi
 fi
